input {
    # Syslog input plugin
    syslog {
        # Setting a port to receive syslog messages
        port => 1515
        type => syslog
        timezone => "America/Chicago"
    }
}

filter {
    ####################################################################################
    # Syslog Data Processing
    ####################################################################################
    # Filter to mutate the event
    mutate {
        # Promote hostname to a top-level "device" field
        copy => { "[host][hostname]" => "device" }
    }
    mutate {
        # Promote ip to a top-level "ip" field
        copy => { "[host][ip]" => "device_ip" }
    }
    mutate {
        # Promote syslog severity name to "level"
        copy => { "[log][syslog][severity][name]" => "level" }
    }
    mutate {
        # Promote syslog severity name to "level"        
        lowercase => [ "level" ]
    }
    mutate {
        # Promote facility name
        copy => { "[log][syslog][facility][name]" => "facility" }
    }
    mutate {
        # Promote process name
        copy => { "[process][name]" => "process_name" }
    }
    mutate {
        # Promote service type
        copy => { "[service][type]" => "service_type" }
    }
}

output {
    ####################################################################################
    # Parsed Syslog Data Outut
    ####################################################################################
    # # Outputs to stdout for debugging
    # stdout {
    #     codec => rubydebug
    # }
    # # Outputs to Loki
    loki {
        url => "http://loki:3100/loki/api/v1/push"
        include_fields => [
            "device",
            "device_ip",
            "level",
            "facility",
            "type",
            "process_name",
            "service_type"
        ]
    }
    # # Outputs to syslog
    # syslog {
    #     host => "localhost"
    #     port => 514
    # }
}
