input {
    # Syslog input plugin
    syslog {
        # Setting a port to receive syslog messages
        port => 1515
        type => syslog
    }
}

filter {
    ####################################################################################
    # Syslog Data Processing
    ####################################################################################
    # Filter to mutate the event
    mutate {
        # Promote hostname to a top-level "device" field
        rename => { "[host][hostname]" => "device" }
    }
    mutate {
        # Promote syslog severity name to "level"
        rename => { "[log][syslog][severity][name]" => "level" }
        lowercase => [ "level" ]
    }
    mutate {
        # Promote facility name
        rename => { "[log][syslog][facility][name]" => "facility" }
    }
}

output {
    ####################################################################################
    # Parsed Syslog Data Outut
    ####################################################################################
    # # Outputs to stdout for debugging
    stdout {
        codec => rubydebug
    }
    # # Outputs to Loki
    loki {
        url => "http://dockworld.ryburn.org:3100/loki/api/v1/push"
        include_fields => [
            "device",
            "level",
            "facility",
            "type"
        ]
    }
    # # Outputs to syslog for forwarding to Kentik
    syslog {
        host => "dockworld.ryburn.org"
        port => 514
    }
}
