# --- INPUTS ---
[[inputs.exec]]
## Commands array running a python script to collect Moen Flo stats
  commands = [["python3", "/scripts/moen_stats.py"]]
  timeout = "10s"
  data_format = "influx"
  interval = "10m"

# Monitors internet speed using speedtest.net service
[[inputs.internet_speed]]
  ## This plugin downloads many MB of data each time it is run. As such
  ## consider setting a higher interval for this plugin to reduce the
  ## demand on your internet connection.
  interval = "30m"
  
  ## override the default metric name
  name_override = "/internet_speed"

  ## Server ID exclude filter
  ## Allows the user to exclude or include specific server IDs received by
  ## speedtest-go. Values in the exclude option will be skipped over. Values in
  ## the include option are the only options that will be picked from.
  ##
  ## See the list of servers speedtest-go will return at:
  ##     https://www.speedtest.net/api/js/servers?engine=js&limit=10
  ##
  # server_id_exclude = []
  server_id_include = ["68610", "2391", "4557"]

# --- OUTPUTS ---
# A plugin that stores metrics in a file
# [[outputs.file]]
#     ## Files to write to, "stdout" is a specially handled file.
#     files = ["stdout", "/etc/telegraf/metrics.out"]
#     data_format = "influx" # Data format to output.
#     influx_sort_fields = false

# A plugin that can transmit metrics to an influx endpoint
[[outputs.influxdb_v2]]
   urls  = ["${KENTIK_API_ENDPOINT}"]
   http_headers = {"X-CH-Auth-Email" = "${KENTIK_API_EMAIL}", "X-CH-Auth-API-Token" = "${KENTIK_API_TOKEN}"}
   user_agent = "kentik"

[[outputs.prometheus_client]]
  # HTTP port to listen on
  listen = ":9004"
